import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import AdminHeader from './components/menubar'
import { getServerSession } from "next-auth";
 import { authOptions } from "@/pages/api/auth/[...nextauth]";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const data = await getServerSession(authOptions);

  return (
    <html lang="en">
        {data?.user.role =='admin' &&
      <body className={inter.className}>
        <AdminHeader />
        {children}</body>
        }
    </html>
  );
}
